- hosts: localhost
  become: yes
  tasks:
    - name: Stop old container if running
      docker_container:
        name: java-app
        state: absent
      ignore_errors: yes

    - name: Run Docker Container
      docker_container:
        name: java-app
        image: java-app:latest
        state: started
        restart_policy: always
        ports:
          - "8081:8080"



