- hosts: localhost
  become: true
  tasks:
    - name: Run Docker Container
      docker_container:
        name: java-app
        image: java-app:latest
        state: started
        ports:
          - "8080:8080"



